### ISSUE TITLE
NOTICE: - Undefined index: global.css

### ISSUE THREAD

**Issue by samkatakouzinos** [optimalisatie/above-the-fold-optimization#10]
> NOTICE: wp-content/plugins/above-the-fold-optimization/includes/critical-css.class.php:578 - Undefined index: global.css
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/twentytwelve/index.php'), get_header, locate_template, load_template, require_once('/themes/twentytwelve/header.php'), wp_head, do_action('wp_head'), WP_Hook->do_action, WP_Hook->apply_filters, Abovethefold_Optimization->header, Abovethefold_Critical_CSS->get 

Above occurs when;
* using new theme 
* admin has not yet saved in wp-admin/themes.php?page=abovethefold&tab=criticalcss for new theme 

I would like this plugin to create a default global.css file (maybe as a php try catch) when; 
* admin selects theme in admin panel 
* visitor views site

**Comment by optimalisatie** [comment]
Hi Sam,

I've added the feature that you requested in `v2.7.6`. The global.css is automatically created when the theme is switched using the action hook [after_switch_theme](https://codex.wordpress.org/Plugin_API/Action_Reference/after_switch_theme).

Best Regards,
Jan Jaap
info@pagespeed.pro
