### ISSUE TITLE
New Optimization Plugin: WordPress WPO Plugin Collection

### ISSUE THREAD

**Issue by optimalisatie** [optimalisatie/above-the-fold-optimization#102]
For access to the latest optimization technologies, check our new **[Website Performance Optimization](https://github.com/o10n-x)** plugin collection. The plugins are easy to install using Github Updater.

![Github Updater](https://github.com/afragen/github-updater/raw/develop/assets/GitHub_Updater_logo_small.png)

# Download: https://github.com/o10n-x

Our old Above The Fold Optimization plugin evolved into a Google PageSpeed score optimization toolkit. Our new WPO plugin collection is a toolkit designed for [Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) score optimization. 

Instead of 1 big optimization plugin, the new WPO plugin format consists of multiple dedicated optimization plugins that can be used together with single plugin performance.

## About the WordPress WPO Collection

The Website Performance Optimization collection includes [CSS](https://github.com/o10n-x/wordpress-css-optimization), [Javascript](https://github.com/o10n-x/wordpress-javascript-optimization), [HTML](https://github.com/o10n-x/wordpress-html-optimization), [Web Font](https://github.com/o10n-x/wordpress-font-optimization), [HTTP/2](https://github.com/o10n-x/wordpress-http2-optimization), [Progressive Web App (Service Worker)](https://github.com/o10n-x/wordpress-pwa-optimization) and [Security Header](https://github.com/o10n-x/wordpress-security-header-optimization) optimization. 

The WPO optimization plugins provide in all essential tools that enable to achieve perfect [Google Lighthouse Test](https://developers.google.com/web/tools/lighthouse/) scores and to validate a website as [Google PWA](https://developers.google.com/web/progressive-web-apps/), an important ranking factor for Google's [Speed Update](https://searchengineland.com/google-speed-update-page-speed-will-become-ranking-factor-mobile-search-289904) (July 2018).

![Google Lighthouse Perfect Performance Scores](https://user-images.githubusercontent.com/8843669/42511142-57ee036a-8451-11e8-97bd-7516158d96d0.jpg)

The WPO optimization plugins are designed to work together with single plugin performance. The plugins provide the latest optimization technologies and many unique innovations.

### JSON configuration

100% of the WPO plugin settings are controlled by JSON. This means that you could use the plugins without ever using the WordPress admin forms.

The JSON is verified using JSON schema's. More info about [JSON schemas](https://github.com/o10n-x/wordpress-o10n-core/tree/master/schemas).

### Local editing of optimization settings

A recently added [Stealth Optimization Config Proxy](https://github.com/o10n-x/wordpress-http2-optimization/releases/tag/0.0.55) concept makes it possible to edit the plugin settings using physical `.json` files from a local editor (with auto upload) making it efficient for fine tuning optimization settings. An update would cost a second compared to using + saving a WordPress admin panel.

https://github.com/o10n-x/wordpress-http2-optimization/releases/tag/0.0.55

## Google PageSpeed vs Google Lighthouse Scores

While a Google PageSpeed 100 score is still of value, websites with a high Google PageSpeed score may score very bad in Google's new [Lighthouse performance test](https://developers.google.com/web/tools/lighthouse/). 

The following scores are for the same site. It shows that a perfect Google PageSpeed score does not correlate to a high Google Lighthouse performance score.

![Perfect Google PageSpeed 100 Score](https://user-images.githubusercontent.com/8843669/42511212-80cac55c-8451-11e8-8761-653913e03e97.png) ![Google Lighthouse Critical Performance Score](https://user-images.githubusercontent.com/8843669/42511211-809e83ac-8451-11e8-9f80-63c8a4ff35e1.png)

### Google PageSpeed score is outdated

For the open web to have a chance of survival in a mobile era it needs to compete with and win from native mobile apps. Google is dependent on the open web for it's advertising revenue. Google therefor seeks a way to secure the open web and the main objective is to rapidly enhance the quality of the open web to meet the standards of native mobile apps.

For SEO it is therefor simple: websites will need to meet the standards set by the [Google Lighthouse Test](https://developers.google.com/web/tools/lighthouse/) (or Google's future new tests). A website with perfect scores will be preferred in search over low performance websites. The officially announced [Google Speed Update](https://searchengineland.com/google-speed-update-page-speed-will-become-ranking-factor-mobile-search-289904) (July 2018) shows that Google is going as far as it can to drive people to enhance the quality to ultra high levels, to meet the quality of, and hopefully beat native mobile apps.

A perfect Google Lighthouse Score includes validation of a website as a [Progressive Web App (PWA)](https://developers.google.com/web/progressive-web-apps/).

Google offers another new website performance test that is much tougher than the Google PageSpeed score. It is based on a AI neural network and it can be accessed on https://testmysite.thinkwithgoogle.com

**Comment by mxmkmarquette** [comment]
where are all plugin it dissappear from your github https://github.com/o10n-x

**Comment by optimalisatie** [comment]
The plugins were made private by a request from the CEO of PageSpeed.pro Ltd., @strayangelfilms. There is currently a conversation with a party who may take over the project and re-brand and re-publish the plugins with an improved quality and including documentation, tutorials and premium support.

There is an option to be involved as test-user/engineer and get access to the private repositories. If you are interested to join the test-team, please send an e-mail to suren@optimization.team.

![image](https://user-images.githubusercontent.com/8843669/43677611-21a3f2a2-9805-11e8-9b64-8e3cb0670ac8.png)

We will provide more information soon!

**Comment by optimalisatie** [comment]
We have made the plugins open source again. They can be used to achieve perfect Google Lighthouse scores which are of high value for SEO.

https://github.com/o10n-x

**Comment by HansVanEijsden** [comment]
Thank you very much.

**Comment by optimalisatie** [comment]
For the record - review after +/- 1 year usage

The WPO / Google Lighthouse optimization plugins are of high quality and are able to deliver results for SEO. Our www.e-scooter.co demo website (started in 2018) ranks in the top 10 in Google in many countries and received visitors from 190 countries. In The Netherlands, www.e-scooter.nl ranks #1 for many scooters. The website is currently at 650k visits per year. The WPO plugins are operating sublimely.

![gogoro-prijs](https://user-images.githubusercontent.com/8843669/48940358-90f40e80-ef17-11e8-8bbb-62c3187d8953.png)

![image](https://user-images.githubusercontent.com/8843669/49431914-c964d980-f7ae-11e8-9a60-f5fb3cfd733d.png)

It will take a bit more effort, and maybe some more feedback from users, but then the WPO plugins could simply be 'perfect' for getting Google Lighthouse 100-scores and even better performance results (speed) than would be required for a 100-score (think of the unique innovations such as timed javascript execution and CSS rendering, advanced Web Worker based preload logic, preload on mouse-down and [Service Worker Push](https://github.com/o10n-x/wordpress-http2-optimization/wiki/HTTP-2-Server-Push-vs-Service-Worker-Push) with better performance than HTTP/2 Server Push).

The plugins could have helped businesses to achieve or maintain online success.
