### ISSUE TITLE
Where shoud I JSON Proxy Config Object?

### ISSUE THREAD

**Issue by utags** [optimalisatie/above-the-fold-optimization#11]
Hi.

Could you please tell me from where should I configure the JSON Proxy Config Object?

**Comment by optimalisatie** [comment]
Hi Utags,

JSON config objects can be used for additional configuration in for example the external resource proxy. You should enter the JSON object on a single line into the applicable field, e.g. `Proxy Preload List`.

The JSON config object for the proxy will enable to match source URLs by regular expression to maintain 1 cache entry for a changing URL.

For example, to match `https://app.analytics.com/file.js?timestamp` to create 1 cache entry for `https://app.analytics.com/file.js` it is possible to use the following JSON config object:

`{"regex": "^https://app\\.analytics\\.com/file\\.js\\?\\d+$", "regex-flags":"i", "url": "https://app.analytics.com/file.js", "expire": "2592000"}`

The JSON config object also contains an optimal parameter `expire`. This is the cache expire time in seconds.

I hope that this information is helpful!

Best Regards,
Jan Jaap
info@pagespeed.pro

p.s. We are currently developing a new plugin that will make configuration more easy and that will offer a lot more features. It will be ready in a few months.

**Comment by utags** [comment]
In my situation I have created following JSON config, for "_https://assets.pinterest.com/js/pinit_main.js_" and "_https://assets.pinterest.com/js/pinit.js_" URLs.

> {"regex": "^https://assets\\.pinterest\\.com/js/pinit_main\\.js\\?\\d+$", "regex-flags":"i", "url": "https://assets.pinterest.com/js/pinit_main.js", "expire": "2592000"}

and

{"regex":"^https:\/\/assets\\.pinterest\\.com\/js\/pinit\\.js\\?\\d+$","regex-flags":"i","url":"https:\/\/assets.pinterest.com\/js\/pinit.js","expire":2592000}

But Google page speed insight still shows me that, "Leverage browser caching" above two pinterest.com URL's

**Comment by optimalisatie** [comment]
What are the source URLs that you want to match? The regex is for URLs with a single integer query string: `https://assets.pinterest.com/js/pinit_main.js?1234567`.

If you want to match a plain URL, you should enter the URL directly without JSON config object.

**Comment by utags** [comment]
Right now this plugin give me following warning. Are there any way to identify which URL's cause this issue? 

"This may indicate that auto-capture captures a script with a changing url that causes a new cache entry to be created on each request.The Proxy configuration page shows a solution to capture scripts with a changing url using a JSON config object."
