### ISSUE TITLE
Extraction of CSS files failing when the CSS files already are optimized to load using js: Failed to retrieve page JSON for critical CSS generator

### ISSUE THREAD

**Issue by josenobile** [optimalisatie/above-the-fold-optimization#16]
Hello, 

I got this error: Failed to retrieve page JSON for critical CSS generator.

The error is originated in includes/extract-full-css.class.php at $stylesheets = $xpath->query('//link[not(self::script or self::noscript)]');

The CSS Files are not included in the common way <link, they are in the form:
`window.Abtf=function(window){var Abtf={cnf:{},h:function(cnf,css){this.cnf=cnf,cnf.proxy&&window.Abtf.proxy_setup(cnf.proxy),this.cnf.js&&!this.cnf.js[1]&&this.js(this.cnf.js[0]);var noref=!("undefined"==typeof this.cnf.noref||!this.cnf.noref);noref||this.ref(),"undefined"!=typeof cnf.gwf&&cnf.gwf[0]&&!cnf.gwf[1]&&("a"===cnf.gwf[0]?this.async(cnf.gwf[2],"webfont"):"undefined"!=typeof WebFont&&("string"==typeof cnf.gwf[0]&&(cnf.gwf[0]=eval("("+cnf.gwf[0]+")")),WebFont.load(cnf.gwf[0])))},f:function(a){a&&this.css&&this.css(),this.cnf.js&&this.cnf.js[1]&&this.js(this.cnf.js[0]),"undefined"!=typeof this.cnf.gwf&&this.cnf.gwf[0]&&this.cnf.gwf[1]&&("a"===this.cnf.gwf[0]?this.async(this.cnf.gwf[2],"webfont"):"undefined"!=typeof WebFont&&WebFont.load(this.cnf.gwf[0]))},ready:function(a,b,c){b=document,c="addEventListener",b[c]?b[c]("DocumentContentLoaded",a):window.attachEvent("onload",a)},ref:function(){"undefined"!=typeof window.console&&console.log("\n%c100","font: 1em sans-serif; color: white; background-color: #079c2d;padding:2px;","Google PageSpeed Score optimized using https://goo.gl/C1gw96\n\nTest your website: https://pagespeed.pro/tests\n\n")},async:function(a,b){!function(c){var d=c.createElement("script");d.src=a,b&&(d.id=b),d.async=!0;var e=c.getElementsByTagName("script")[0];if(e)e.parentNode.insertBefore(d,e);else{var f=document.head||document.getElementsByTagName("head")[0];f.appendChild(d)}}(document)}},SITE_URL,BASE_URL_REGEX;return Abtf}(window);!function(a,b){var c,d,e=!1,f=!1,g=!1,h=!1,i=!1,j=!1,k=!1,l=!1,m=[],n=[],o=[],p={},q=[];a.Abtf.proxy_setup=function(a){if("undefined"==typeof b)var b=!1;if(c=a.url||b,e=a.js||!1,f=a.css||!1,g=a.cdn||!1,g&&q.push(g),h=a.js_include||!1,i=a.js_exclude||!1,j=a.css_include||!1,k=a.css_exclude||!1,a.preload){l=!0;for(var r=0;r<a.preload.length;r++)"regex"===a.preload[r][0]?(o.push([a.preload[r][2],a.preload[r][3],a.preload[r][1]]),a.preload[r][4]&&(p[a.preload[r][0]]=a.preload[r][4],q.indexOf(a.preload[r][4])===-1&&q.push(a.preload[r][4]))):(m.push(a.preload[r][0]),n.push(a.preload[r][1]),a.preload[r][4]&&(p[a.preload[r][0]]=a.preload[r][4],q.indexOf(a.preload[r][4])===-1&&q.push(a.preload[r][4])));d=a.base||!1}if(0===q.length)q=!1;else for(var s=q.length,r=0;r<s;r++)q[r]=v(q[r])};var r={Element:"undefined"!=typeof Element&&Element,Document:"undefined"!=typeof Document&&Document},s={append:{},insert:{}};for(var t in r)r.hasOwnProperty(t)&&r[t]&&(s.append[t]=r[t].prototype.appendChild,s.insert[t]=r[t].prototype.insertBefore);var u=document.createElement("a");u.href=document.location.href;var v=function(a){var b=document.createElement("a");return b.href=a,b},w=function(a,b){return"css"===b?c.replace("{PROXY:URL}",escape(a)).replace("{PROXY:TYPE}",escape(b)):"js"===b?c.replace("{PROXY:URL}",escape(a)).replace("{PROXY:TYPE}",escape(b)):void 0},x=function(a,c){if(l){var e=m.indexOf(a);if(e>-1)var f=n[e];else if(o.length>0)for(var g,h,i=o.length,j=0;j<i;j++){h=!1;try{g=new RegExp(o[j][0],o[j][1]||"")}catch(a){h=!0}if(!h&&g.test(a)){o[j][2]?f=o[j][2]:o[j][3]&&(a=o[j][3]);break}}if(f){if("undefined"!=typeof p[a])var k=p[a];else var k=d;k+=f.substr(0,2)+"/",k+=f.substr(2,2)+"/",k+=f.substr(4,2)+"/",k+=f;if("js"===c){if(k+=".js","undefined"!=typeof b.cachedScriptUrl){var q=v(k).href;k=b.cachedScriptUrl(q)}}else"css"===c&&(k+=".css");return k}}if("js"===c&&"undefined"!=typeof b.cachedScriptUrl){var r=v(a).href;if(a=b.cachedScriptUrl(r),a!==r)return a}return w(a,c)},y=function(a,b){var c="object"==typeof a&&"undefined"!=typeof a.href?a:v(a);if("blob:"===c.protocol)return!1;if(q&&b!==!0)for(var d=q.length,e=0;e<d;e++)if(c.href.indexOf(q[e].href)!==-1)return!1;return c.host!==u.host},z=function(a){var b="object"==typeof a&&"undefined"!=typeof a.href?a:v(a);if("blob:"===b.protocol)return!0;if(h){for(var c=!1,d=h.length,e=0;e<d;e++)if(b.href.indexOf(h[e])!==-1){c=!0;break}if(!c)return!0}if(i)for(var d=i.length,e=0;e<d;e++)if(b.href.indexOf(i[e])!==-1)return!0;return!1},A=function(a){var b="object"==typeof a&&"undefined"!=typeof a.href?a:v(a);if("blob:"===b.protocol)return!1;if(q)for(var c=q.length,d=0;d<c;d++)if(b.href.indexOf(q[d].href)!==-1)return!1;return b.host!==u.host},B=function(a){var b="object"==typeof a&&"undefined"!=typeof a.href?a:v(a);if("blob:"===b.protocol)return!0;if(j){for(var c=!1,d=j.length,e=0;e<d;e++)if(b.href.indexOf(j[e])!==-1){c=!0;break}if(!c)return!0}if(k)for(var d=k.length,e=0;e<d;e++)if(b.href.indexOf(k[e])!==-1)return!0;return!1},C=function(a){if(a.nodeName)if("SCRIPT"===a.nodeName.toUpperCase()){if(!e)return!1;if("abtf"===a.getAttribute("rel"))return a.removeAttribute("rel"),!1;if(a.src){var c=v(a.src);if(z(c))return!1;if(!y(c)){if("undefined"!=typeof b.cachedScriptUrl){if("blob:"===c.protocol)return!1;url=b.cachedScriptUrl(c.href),url!==c.href&&(a.src=url)}return!1}return"js"}}else if("LINK"===a.nodeName.toUpperCase()&&"stylesheet"===a.rel.toLowerCase()){if(!f)return!1;if("abtf"===a.getAttribute("rel"))return a.removeAttribute("rel"),!1;if(a.href){var c=v(a.href);return!B(c)&&(!!A(c)&&"css")}}return!1},D=function(a){var b=C(a);if(!b)return!1;var c=v("css"===b?a.href:a.src).href,d=x(c,b);"css"===b?a.href=d:"js"===b&&(a.src=d)},E={appendChild:function(a,b){return D(b),s.append[a].call(this,b)},insertBefore:function(a,b,c){return D(b),s.insert[a].call(this,b,c)}};
`
That means, the same plugin already optimized the CSS load, but is trying to get the CSS in the previous way.

I suggest using for example phantomjs to detect the real loaded CSS, or get the CSS using the Wordpress API. The phantomjs solution is more resilient against CSS files loaded in any way.

**Comment by optimalisatie** [comment]
Hi Josenobile,

Thank you for reporting the problem!

Regarding the failure to extract full CSS. It is unrelated to the async javascript code. The (JSON) page for extracting full CSS does not contain the async javascript code but the original links to the CSS files.

The problem may be related to a conflict with a different plugin. Have you checked the server logs to see if a corresponding error is visible?

Regarding the PhantomJS solutions. Regrettably that isn't available in PHP. However, we are developing a new plugin that will contain a solution that is both perfect / stable and performance wise efficient. It will be better than PhantomJS.

Best Regards,
Jan Jaap
info@pagespeed.pro
