### ISSUE TITLE
Above The Fold Optimization - New  Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by marcelle29** [optimalisatie/above-the-fold-optimization#17]
Hi,

I've just installed your Above The Fold plugin, but am getting the following error when trying to activate:

Parse error: syntax error, unexpected T_FUNCTION in /home/sites/easyas123accounts.co.uk/public_html/wp-content/plugins/above-the-fold-optimization/includes/webfonts.class.php on line 368

I've reinstalled 3 times, and have deactivated all but essential plugins. This plugin works fantastically well on my other website (100%), both built using Wordpress Cherry theme. Your help would be greatly appreciated, thank you.

**Comment by optimalisatie** [comment]
Hi marcelle29,

What version of PHP are you using? 

Best Regards,
Jan Jaap
info@pagespeed.pro
