### ISSUE TITLE
cannot save the critical css

### ISSUE THREAD

**Issue by vucumbra** [optimalisatie/above-the-fold-optimization#19]
Hi
i have extract my full css
and then i have used this tool for critical css
https://jonassebastianohlsson.com/criticalpathcssgenerator/

when i save, i was redirect to error 404
how can i solve this?
thx

**Comment by optimalisatie** [comment]
Hi vucumbra!

Thank you for taking the time to report the problem!

We did not experience the issue before. My first suggestion would be that an other plugin, for example a security plugin, is causing the problem. As you’ve already tested for conflicts it may be a server configuration based security. For example, Plesk panel restricts access to /wp-includes/ that causes javascript to fail in WordPress v4.7.

Do you have access to the server logs and have you checked if an error is logged?

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by vucumbra** [comment]
i can' access to server log
if i put some code in critical css, 2-3 line ok saved
but if i put all critical css i'm redirect to error 404

**Comment by optimalisatie** [comment]
If saving a small amount of critical CSS works, it is most likely a security related issue. The server is forcing a redirect or 404 error based on the input size.

My advise is to request support from the hosting provider to discover the exact cause in the server log.
