### ISSUE TITLE
Failed to retrieve page JSON for critical CSS generator.

### ISSUE THREAD

**Issue by mindlek** [optimalisatie/above-the-fold-optimization#22]
I’ve moved to a new hosting then uploaded all the files, transferred database.
Later I installed nodejs and all the npm packages.
When I clicked on “install package” button I got this error.

Failed to retrieve page JSON for critical CSS generator.

I’ve been trying to find the problem, checking debug, errors but none found including deleted and reinstalled, even found some cache then deleted from database but still no luck.

Also I’ve noticed that the task name that I used last time is still there.

Please have a look and guide me. I really like your tool as I’m not an advanced user and very new to Gulp so I don’t know what to do now.

**Comment by optimalisatie** [comment]
Hi mindlek,

The error is not related to the package or Gulp.js, it means that WordPress PHP is unable to access the URL of a page on your website to extract JSON data of a page. The most likely explanation considering the recent server move is that the WordPress URL is incorrectly configured or that access to the domain / website from the local machine is blocked. 

You can test for a server access issue with the following CLI command: `wget https://your-website.com/`. If the download succeeds and if the content matches, the server access is not the problem.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by mindlek** [comment]
Hi Jan,

Thank you for your reply. You are right it's from your wonderful plugin but it's me.
I made a mistake set up my VPS. Now it works perfectly.

Another thing that I'm struggling is to set up conditional rules as my home page uses only 1 stylishness and there are 4 on the others so I don't need too many on homepage for first load time for clients.

Would you have a example JSON file or else?

 Best regards,
Tom

**Comment by optimalisatie** [comment]
Hi Tom,

Conditional CSS can be used to create tailored critical CSS for different pages, for example different critical CSS for the front page and for blog message pages.

When you want to add critical CSS specifically for the front page, simply create a condition with "frontpage" as condition and enter the unique critical CSS to be used on the front page.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by earcos** [comment]
Hi, I am having the exact same problem, but in my case we didn't changed hosts. Package creation was working fine yesterday but today is failing with that exact error. wget works, so this is not about server access problems.

**Comment by trillrit** [comment]
@earcos check error logs, it might be helpful... in my case **mbstring** php module was missing
