### ISSUE TITLE
Full CSS Extraction says all local CSS files are 0.00B

### ISSUE THREAD

**Issue by maiksch** [optimalisatie/above-the-fold-optimization#23]
For some reason I can't create a critical path CSS because my critical.css always ends up empty. 

After trying to extract my full CSS I discovered that the plugin thinks all of my local CSS files are empty (e.g. http://localhost/wordpress/wp-content/themes/my-test-theme/style.css (0.00B) - Media: all), even though they are not. 
The only CSS file that is recognised is this one: https://fonts.googleapis.com/css?family=Lato%7CRoboto+Slab&ver=4.7.2 (3.04kB) - Media: all

Is there something going on with the plugin or is it some configuration problem? I don't use any other compression or minifying plugin besides Above The Fold Optimization

**Comment by optimalisatie** [comment]
Hi Smadback,

It appears that access to your CSS files is denied. It may be a server security related issue.

Do you have access to the server log (PHP errors) and if so, is any information visible related to the issue?

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by Smadback** [comment]
Hi,

here is what I found: http://pastebin.com/dpeQ3Nrz

It seems that the paths where the plugin looks for the CSS files are wrong:
D:\Program Files (x86)\xampp\htdocs\garntante/garntante/wp-content/themes/my-sass-theme/style.css
where it should be:
D:\Program Files (x86)\xampp\htdocs\garntante\wp-content\themes\my-sass-theme/styles.css

Where can correct set this?

**Comment by optimalisatie** [comment]
Hi Smadback,

It appears to be related to the path returned by the WordPress function [get_template_directory_uri()](https://codex.wordpress.org/Function_Reference/get_stylesheet_directory_uri). This is based on a WordPress configuration setting and it could be modified by a WordPress filter (by a different plugin). It is not likely a bug related to the ABTF plugin.

Regarding the creation of critical CSS, it is possible to create it locally and update it via the text field.

Best Regards,
Jan Jaap
info@pagespeed.pro
