### ISSUE TITLE
rel="abtf" produces invalid w3c code

### ISSUE THREAD

**Issue by azirer** [optimalisatie/above-the-fold-optimization#24]
I noticed today that the `rel="abtf"` in the script and style references produces invalid html code. I guess the plugin can work without it or just ids whenever possible (?)

**Comment by optimalisatie** [comment]
Hi azirer,

Thank you for your bug report / feedback!

The issue wlll be solved in the next update of the plugin.

Best Regards,
Jan Jaap
info@pagespeed.pro
