### ISSUE TITLE
 Optimize Javascript Loading

### ISSUE THREAD

**Issue by azirer** [optimalisatie/above-the-fold-optimization#28]
I'm experimenting with javascript loading optimization. Currently I use the `little-loader` option with `Abide Dependencies` and `jQuery Stub` checked. `Position` at the header.
My page breaks at one inline script of the layerslider plugin. The error is `Uncaught TypeError: Cannot read property 'layerSlider' of undefined` and the inline scripts contain this among others at the footer:

`<script data-cfasync="false" type="text/javascript">
            var lsjQuery = jQuery;
 </script>
<script data-cfasync="false" type="text/javascript">
lsjQuery(document).ready(function() { if(typeof lsjQuery.fn.layerSlider == some more stuff here....
 </script>`

I tried several options but none seemed to work so far. Any ideas? 
Moreover can you explain how to use the Async Force List	and what is the difference between Async Disabled List and  Ignore List?

**Comment by optimalisatie** [comment]
Hi azirer,

The issue is related to async loading of jQuery. lsjQuery becomes a reference to the jQuery Stub and therefor the layerSlider extension is lost after loading jQuery. 

A quick solution would be to encapsulate the code in `jQuery(function($) { ... });` This could be done with a filter:

```php
function pagespeed_filter_html($searchreplace)
{
    list($search, $replace, $search_regex, $replace_regex) = $searchreplace;

    # rewrite lsjQuery .ready() code
    $search_regex[] = '|lsjQuery\([^\.]*\.ready[^\{]+\{(.*?)else\s*\{(.*?)\}\s*\}\s*\);|s';
    $replace_regex[] = 'jQuery(function($) { ... });';

    # replace lsjQuery references to original jQuery
    $search_regex[] = '#lsjQuery([\(|\.])#Ui';
    $replace_regex[] = 'jQuery$1';

    return array($search,$replace,$search_regex,$replace_regex);
}
add_filter('abtf_html_replace', 'pagespeed_filter_html', 10, 1);
```

If you use Autoptimize for minification of inline javascript you could use a filter by Autoptimize:

```php
function pagespeed_filter_inline_js($JS)
{
    if (strpos($JS, 'lsjQuery') !== false) {
        $JS = preg_replace('|lsjQuery\([^\.]*\.ready[^\{]+\{(.*?)else\s*\{(.*?)\}\s*\}\s*\);|s', 'jQuery(function($) { ... });', $JS);
        $JS = preg_replace('#lsjQuery([\(|\.])#Ui', 'jQuery$1', $JS);
    }
    return $JS;
}
add_filter('autoptimize_js_after_minify', 'pagespeed_filter_inline_js', 10, 2);
```

**Comment by azirer** [comment]
Thank you for your answer it was about time to study some exp stuff. I used the first method and now I did that and now I don;t get any javascript errors. However the
`jQuery(function($) { code_here_different_on_every_page });` doesn't seem to execute although it is valid. If I type at the console `code_here_different_on_every_page` it runs as it should to.

I thought to enqueue at the very end of my page all that code but that code contains the id and the options of the  sliders and it is different on every page. Any ideas? The  `code_here_different_on_every_page` seems like that

```
<script data-cfasync="false" type="text/javascript">jQuery(function($) {
jQuery("#layerslider_2").layerSlider({hideOnMobile: true, startInViewport: false, pauseOnHover: false, animateFirstSlide: false, forceLoopNum: false, skin: 'borderlessdark3d', thumbnailNavigation: 'disabled', autoPlayVideos: false, cbInit: function(element) { }, cbStart: function(data) { }, cbStop: function(data) { }, cbPause: function(data) { }, cbAnimStart: function(data) { }, cbAnimStop: function(data) { }, cbPrev: function(data) { }, cbNext: function(data) { }, skinsPath: 'https://example.com/wp-content/layerslider/static/skins/css/borderlessdark3d.css'})
});</script>
```
