### ISSUE TITLE
Concatenate and load async all inline javascript

### ISSUE THREAD

**Issue by azirer** [optimalisatie/above-the-fold-optimization#29]
This is rather a question or suggestion but sometimes may refer to issues like this one https://github.com/optimalisatie/above-the-fold-optimization/issues/28

A webpage has this structure regarding javascript
```
<head>
<script>inline-head-script1</script>
<script>inline-head-script2</script>
<script src="/ext-head-script1.js"></script>
<script src="/ext-head-script2.js"></script>
</head>
<body>
...
<script>inline-body-script1</script>
<script src="/ext-footer-script1.js"></script>
<script src="/ext-footer-script2.js"></script>
<script>inline-body-script2</script>
</body>
```

The plugin optimizes javascript by serving it asynchronously either in the footer or in the header. Because of the async, the location doesn't really matter. 
Question: **Why not concatenate all inline body javascript into an external file for each page and load it async so that we can defer all js files that the inline JS depends on?**

For example
```
<head>
<script>inline-head-script1</script>
<script>inline-head-script2</script>
</head>
<body>
...


<script async src="/ext-head-script1.js"></script>
<script async src="/ext-head-script2.js"></script>
<script async src="/ext-footer-script1.js"></script>
<script async src="/ext-footer-script2.js"></script>
<script async src="/cache/inline-body-script1+inline-body-script2-hash.js"></script>
</body>
```

Something like this (Concatenate and load async all inline body javascript) could be added as an option. I understand that sometimes it might break things for example when `inline-body-script1.js` need to run before `/ext-footer-script1.js` but usually all inline JS in wordpress plugins and themes make jQuery (or other libraries) modifications so they need to be loaded after the external libraries. I think in most cases it doesn't matter loading all libraries first an then execute the inline JS. Therefore I think that the option above combined with `Abide Dependencies` would improve things in most cases. 

A more extreme example could be to make external each single block of inline JS but it makes things more complicated and maybe it is not a wise option even in http/2

**Comment by optimalisatie** [comment]
Hi azirer,

Javascript concatenation, minification and optimization will be part of our new plugin that should be available by May / July 2017. It will contain unique solutions to achieve the best possible performance and it will enable Google Closure Compiler based javascript optimization:

https://developers.google.com/closure/compiler/

The result of Google Closure Compiler is not just a smaller size that UglifyJS (and far better than PHP based solutions) but also improved Javascript speed (code optimization).

We will include a unique javascript loader innovation based on HTML5 Fetch API (with AJAX / XHR stream fallback for old browsers) that will enable per file javascript loading with a single download (1 fast / optimized request for all javascript data while files are executed directly once the data has been transferred), combined with localStorage cache to save requests/increase speed for returning users and during navigation. It will enable the best possible javascript loading and render performance result in all situations (for first, returning and navigation requests). It is a unique solution, it has never been done before.

The javascript loader and compressor will contain a javascript source map that allows for debugging of the original files, as if the files were loaded as originally configured by WordPress.

Best Regards,
Jan Jaap
info@pagespeed.pro
