### ISSUE TITLE
Avoid 666 permissions for files and 777 for folders 

### ISSUE THREAD

**Issue by azirer** [optimalisatie/above-the-fold-optimization#30]
There are folders like caches, proxies etc. that have 777 permissions and there are files generated js and css files with 666 permissions.

I think that anything which allows public write is dangerous so the maximum permissions set on folders shouldn't exceed the 755 and for files the 664. This will work on every setup

**Comment by optimalisatie** [comment]
Hi azirer,

Thank you for reporting the problem and for your suggestion! The issues will be fixed in the next update!

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by Flatshift** [comment]
Just got a notice from my host I had dir/files with insecure 777 permissions, and found /wp-content/cache/abtf/ with everything 777. 
Manually corrected the permissions, and disabled proxy settings for now, which should prevent abtf from creating any new dir and files with such vulnerable permissions.

**Comment by azirer** [comment]
I have a cron for this but it's rather a hack than a solution. 

Jan is the update going to be released soon?

Thank you
