### ISSUE TITLE
Problems with Nextgen lightbox and WP-Colorbox popup

### ISSUE THREAD

**Issue by johanna52** [optimalisatie/above-the-fold-optimization#31]
Hi everybody,
I installed this plugin and got it to work. Pagespeed Insights is very happy. Pingdom Tools doesn't show any progress in the loading time though.
But my problems now are, that the photos showed in the Nextgen Fancybox and Thickbox aren't displayed in the lightbox anymore. Example here: https://www.tina-turner.nl/blog/photos/
The same with the WP-Colorbox. I have videos and photos that should be displayed in a popup box, but that doesn't happen anymore. Example here: https://www.tina-turner.nl/blog/1985-2/
I already tried to exclude some css and js files, but that didn't work.
Is there an option to exclude entire plugins?

Johanna

**Comment by optimalisatie** [comment]
Hi Johanna,

Thank you for your time to report the problem!

It appears that there are several javascript issues on your website that are related to the mentioned plugins. 

![tina-turner1](https://cloud.githubusercontent.com/assets/8843669/23823535/bc0626d2-0664-11e7-8f51-a1dcf4620b42.png)

![tina-turner2](https://cloud.githubusercontent.com/assets/8843669/23823536/c12c3c00-0664-11e7-8e26-d6f3a0d0496a.png)


It may be that the option jQuery Stub (Javascript Optimization tab) solves the issues, however, it may require advanced tuning of the settings and/or custom frontend optimization using WordPress filters.

A solution that may resolve the specific issues quickly is by using the javascript minification plugin Autoptimize with the advanced option `Also aggregate inline JS?`.

I hope that this information is helpful. Please let me know if you manage to have the issues resolved!

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by johanna52** [comment]
Hi Jan Jaap,
Thanks for the speedy answer.
Unfortunately your solutions didn't work.
For now I have disabled the javascript option in your plugin, but that isn't a real solution of course.
If somebody has a possible solution, please let me know.

Johanna

**Comment by optimalisatie** [comment]
Although it is not a perfect solution, the problems may be resolved by excluding jQuery from async loading.

Using Autoptimize + inline javascript minification may be the best solution to persue. Were there new errors visible when using that solution?

**Comment by johanna52** [comment]
I got rid of the jquert errors by using:
`Script loader:
 little-loader + HTML5 Web Worker and Fetch API based script loader with localStorage cache`

Autoptimize didn't improve anything so I disabled that.
The only error I have now is this: `Uncaught TypeError: Cannot read property 'setDefaults' of undefined
    at HTMLDocument.<anonymous> (https://www.tina-turner.nl/blog/photos/:2294:58)
    at i (blob:https://www.tina-turner.nl/50348b5f-cfc4-40e7-ae6f-ca8c6cb0f847:5:27449)
    at Object.fireWith [as resolveWith] (blob:https://www.tina-turner.nl/50348b5f-cfc4-40e7-ae6f-ca8c6cb0f847:5:28213)
    at Function.ready (blob:https://www.tina-turner.nl/50348b5f-cfc4-40e7-ae6f-ca8c6cb0f847:5:30006)
    at HTMLDocument.K (blob:https://www.tina-turner.nl/50348b5f-cfc4-40e7-ae6f-ca8c6cb0f847:5:30368)`

The lightbox and colorbox popups still aren't working;
But you can see for yourself here: https://www.tina-turner.nl/blog/photos/ and here: https://www.tina-turner.nl/blog/1985-2/
I will leave it like this till tomorrow. If I can't get it to work then, I will have to let go of this plugin.
Too bad, because the pagespeed insights improved greatly.  Just have to check pindom tools tomorrow again, because that didn't improve.

Johanna

**Comment by johanna52** [comment]
I disabled your plugin for now.
I found out my website was displayed not well at all on mobil phones and tablets.

Johanna

**Comment by johanna52** [comment]
I investigated this a bit more and on another site of mine (with the Custom Theme, child theme from Omega from Theme Hall: https://themehall.com/custom-free-omega-child-theme-wordpress) the Nextgen Gallery Lightbox works fine.
The WP-Colorbox plugin does also work with popup videos, but it doesn't work with popup images.
So it is a combination of the theme and which plugins you use.
I am using the Tempera Theme from Cryout Creations: https://www.cryoutcreations.eu/wordpress-themes/tempera
But I have no idea what to do next, so for now I will leave it.
If somebody has a solution, please let me know.

Johanna

**Comment by jonathan-misfitcdo** [comment]
hi Johanna got any solution on Nextgen Gallery Lightbox not showing popups got same error when I enable javascript optimization
