### ISSUE TITLE
Uncaught PHP Error caused by undefined is_amp_endpoint()

### ISSUE THREAD

**Issue by 16patsle** [optimalisatie/above-the-fold-optimization#32]
Hi! Today I encountered a fatal error in the error log on my wordpress site that seems to be cause by this plugin checking if the current url is an amp url in the W3TC integration. Because some member function is undefined, it throws the following error (file paths shortened/replaced with /wordpress/ to save space):

```
PHP Fatal error: Uncaught Error: Call to a member function get() on null in /wordpress/wp-includes/query.php:28
Stack trace:
#0 /wordpress/wp-content/plugins/amp/includes/amp-helper-functions.php(42): get_query_var('AMP_QUERY_VAR', false)
#1 /wordpress/wp-content/plugins/above-the-fold-optimization/includes/abovethefold.class.php(213): is_amp_endpoint()
#2 /wordpress/wp-content/plugins/above-the-fold-optimization/includes/optimization.class.php(355): Abovethefold->is_enabled()
#3 /wordpress/wp-content/plugins/above-the-fold-optimization/modules/plugins/w3-total-cache.inc.php(278): Abovethefold_Optimization->process_output_buffer('REMOTE_ADDR')
#4 [internal function]: Abovethefold_OPP_W3TotalCache->ob_callback('REMOTE_ADDR')
#5 /wordpress/wp-content/plugins/w3-total-cache/Util_Bus.php(21): call_user_func(Array, 'REMOTE_ADDR')
#6 {ROOT URL} in /wordpress/wp-includes/query.php on line 28
```

I am using the W3TC Fixed v0.9.5.2.3 along with Above The Fold Optimization v2.7.10 on WordPress 4.7.3.

There was/is a similar issue in W3TC, which was [fixed in the community version](https://github.com/szepeviktor/w3-total-cache-fixed/pull/370), so that may give some hints if needed.

This doesn't seem to cause any direct trouble with the site, but as I just noticed it today, I can't be sure. I hope you can fix this without too much trouble.

**Comment by optimalisatie** [comment]
Hi 16patsie,

Thank you for reporting the issue!

The Above The Fold Optimization plugin is disabled on AMP pages using the following check in `/includes/abovethefold.class.php` line 208:

```php
/**
 * Check if optimization should be applied to output
 */
public function is_enabled() {

	/**
	 * Disable for Google AMP pages
	 */
	if (function_exists('is_amp_endpoint') && is_amp_endpoint()) {
		return false;
	}
```

The cause of the issue is originated in the function "is_amp_endpoint()".

I noticed in one of your other topics that was discovered that the is_amp_endpoint() requires a WordPress database object to be present. 

https://github.com/Automattic/amp-wp/issues/608

Do you know of a reason why the WordPress database object would be unavailable at plugin level?

https://codex.wordpress.org/Class_Reference/wpdb

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by 16patsle** [comment]
I have no idea currently, but I'm taking a look in the source code for the AMP plugin to see if there is anything there that could help.

What I really don't understand is why the is_amp_enpoint() would cause problems, as I'm fairly certain the AMP pages on my sites are not used that much. At least it doesn't log an error if I manually visit them.

**Comment by 16patsle** [comment]
I can't really find a reason why WP_Query is null. It is supposed to be a global, but is it possible that it somehow is unavailable?
