### ISSUE TITLE
Trying to get Critical CSS Creator to work

### ISSUE THREAD

**Issue by Const4ntFlux** [optimalisatie/above-the-fold-optimization#35]
I'm trying to generate my critical css via your instruction in the WordPress plugin settings, but since I am a newbie, I fail. :(

Here is what I'm doing:
1. Used "Create a Gulp.js Critical CSS Task Package" to download my package
2. Getting started: Step 1 follow installation instructions ->

Installation:
4. Installed node.js via the download at https://nodejs.org/en/ for Mac OS. (download, double-click, following installation instructions)
5. Started Terminal, entered: npm install `--global gulp-cli` to install gulp.js and let it run.

6. Step 1: Clicked Auto install to install package.json and gulpfile.js
7. Step 2: Started Terminal and opened remote ssh to my server and navigated to `/wp-content/themes/THEME_NAME/abovethefold/`
8. Step 3: typed `npm install`

Terminal output: `-shell: npm: command not found`

This leads me to believe I have to install node.js and gulp.js not locally but on the remote server.
If this is the case, how can I do that?
And if not, what am I missing?

Thanks!

**Comment by optimalisatie** [comment]
Hi Const4ntFlux,

It is correct that for automated update of the WordPress critical CSS it is required to install gulp / Node.js on the remote server. It is an option however to start with manual creation to test the configuration, and when it is perfectly setup, install a server side installation for continued (more efficient) critical CSS maintenance.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by Const4ntFlux** [comment]
Oh! This section of the plug-in setup is for automatically created critical css? That is pretty nifty.
However, I would settle with creating a critical css manually for now.

So the server side installation is only needed for this? How can I manually create the critical css?
I already tried several online tools to create the css and manually enter it in AtF, but it never really worked since the css always seem to be missing something.
Thanks!
