### ISSUE TITLE
Adding conditional critical path css — filters

### ISSUE THREAD

**Issue by dalelowry** [optimalisatie/above-the-fold-optimization#36]
I've identified the critical path css for different pages on my site. I have two major types of page designs requiring different critical path css.

Creating the filter for the first group was easy because it only involved three pages. For the other group, I want one that's "all pages but those three," but it's not clear to me how to go about that. I assume it would be by creating a custom filter condition like "filter:your_filter_function", but what language should the function be in? PHP?

Of course, if the GLOBAL CSS applies only to pages that aren't listed in the Conditional Critical Path CSS section, I could just insert the critical css there—but my assumption has been that Global means global and will override conditional critical css.

If there's a guide somewhere, please link me. Thanks!

**Comment by optimalisatie** [comment]
Hi @dalelowry,

Our apologies for the late reply. 

We don't have documentation yet. We are currently developing a new plugin that will provide many new optimization features including minification and concatenation of CSS files. It will include documentation.

We've had some funding issues but our engineers are working full time again so we do our best to have the new plugin completed a.s.a.p. It will be called Advanced WordPress Optimization.

To create the custom condition that you need, the filter option could be used. It is similar to a WordPress (PHP) filter function.

To exclude 3 pages and include all other pages, the following filter could be used (include in /theme/functions.php):

```php
/**
 * Critical CSS Condition
 * Match all except 3 pages
 */
function themename_criticalcss_condition( $params = array() ) {

	// Page 10, 22 or 391?
	if (is_page([10,22,391])) {
		return false; // no match
	}

	return true; // match
}
```

In the filter configuration you can then select the condition by typing `filter:themename_criticalcss_condition`.

![image](https://user-images.githubusercontent.com/8843669/28587022-fa7626d4-7175-11e7-8634-db2f1ca78312.png)

Best Regards,
Jan Jaap
info@pagespeed.pro
