### ISSUE TITLE
Getting 404 error when adding Critical CSS

### ISSUE THREAD

**Issue by marcel-za** [optimalisatie/above-the-fold-optimization#38]
I can add a few lines to the Critical CSS section, but when I add more than a few, I get a 404 error.

I've tried disabling all plugins, but still get the error.

**Comment by optimalisatie** [comment]
Hi @marcel-za,

Our apologies for the late reply.

Please let us know if you still need help with the issue. We've had one similar complaint before, the cause then appeared to be Lightspeed server based security configuration that was intended for the frontend and was incorrectly applied to the backend (`/wp-admin/`).

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by vucumbra** [comment]
i have the same error but not have understand how solve
