### ISSUE TITLE
Combining all CSS files?

### ISSUE THREAD

**Issue by ghost** [optimalisatie/above-the-fold-optimization#39]
Hey guys, great plugin, gave you 5 stars in WP plugin page because it is the only plugin who worked for me best wihtout of asking a premium membership (seems to me greedy to ask and noble not to ask in a free software community bu that's just my opinion maybe for another discussion).

Anyway, I do encounter only one problem with the plugin:

My GPI score raised drastically but still lists a very long list of CSS files. 

If I use the plugin CSS minify I can combine all of these in one file and then GPI lsits only this long CSS file.

My question is this:

Can you please add a "combine all CSS files" option?

**Comment by optimalisatie** [comment]
Hi @Benqzq,

Our apologies for the late reply. 

We are currently developing a new plugin that will provide many new optimization features including minification and concatenation of CSS files. 

We've had some funding issues but our engineers are working full time again so we do our best to have the new plugin completed a.s.a.p. It will be called Advanced WordPress Optimization.

Best Regards,
Jan Jaap
info@pagespeed.pro
