### ISSUE TITLE
Above the fold - FOUC 

### ISSUE THREAD

**Issue by swannykhc** [optimalisatie/above-the-fold-optimization#41]
First i downloaded the autoptimize plugin then follow by above the fold optimization. Thereafter i installed better wordpress minify plugins .

I realised the FOUC appears after i installed above the fold. Any solution?

It does help improves my speed alot using pagespeed insights to check. However, how & where to check the critical CSS matching with the full css view?

**Comment by optimalisatie** [comment]
Hi Swanny,

Thank you for continuing the [WordPress support topic](https://wordpress.org/support/topic/text-came-out-instead-of-my-home-image-landing-page/) on Github!

Regarding your question: You will find the Critical CSS Quality Test in the "PageSpeed menu". 

Did you create critical CSS and if so, what method did you use? 

You can find more information about creating critical CSS in the following article by a Google engineer:

https://github.com/addyosmani/critical-path-css-tools

**Comment by swannykhc** [comment]
Hi

Sorry my question is there is FOUC appears after installed Above the fold optimisation?
How do i remove the FOUC . It is distracting the website appearance. 

I am not sure did i create critical css? And it is have fo do with the FOUC appearing?

**Comment by swannykhc** [comment]
Hi,

I have use Critical Path CSS Generator to minify my css file . But I am still getting the FOUC (Digit 1,2,3,4,5) appear in my scream before images is loading.

Any solution out there? appreciate.

**Comment by optimalisatie** [comment]
Hi Swanny,

Have you tried the Critical CSS Quality Test and are both screens the same? If not, it means that the critical CSS is not valid and it would be required to improve it.

**Comment by swannykhc** [comment]
If both screens are the same but still get FOUC?
Thanks
