### ISSUE TITLE
Proxy Directory growing to hundreds of Mb

### ISSUE THREAD

**Issue by jiiins** [optimalisatie/above-the-fold-optimization#42]
I just realized that the /wp-content/uploads/abovethefold/proxy started growing to hundreds of thousands of subdirs, taking hundreds of Mb (800 at the last check).

By disabling the JS Proxy feature it stops growing, and re-activating it lets it grow again.

The only change I made to the site was installing the official AMP plugin and the AMP for WP plugin the day before, but I'm not sure if it's just a coincidence.

**Comment by optimalisatie** [comment]
Hi jiiins,

If you use auto capture to proxy any script and if the website contains a script with a changing URL, e.g. a time stamp query string, it would cause a new cache entry to be created on every request. The configuration page shows a solution to capture such scripts using a JSON config object.

> **JSON Proxy Config Object**
>     JSON config objects enable advanced file based proxy configuration. JSON objects can be used together with simple file entry and must be placed on one line (no spaces are allowed).
>     JSON config objects must contain a target url (the url that will be downloaded by the proxy). Regular expression enables to match a source URL in the HTML, e.g. an URL with a cache busting date string (?time) or an url on a different host. Valid parameters are url, regex, regex-flags, cdn and expire (expire time in seconds).
>     Example:
>     {"regex": "^https://app\\.analytics\\.com/file\\.js\\?\\d+$", "regex-flags":"i", "url": "https://app.analytics.com/file.js", "expire": "2592000"}

The regex in the example will capture scripts with the url https://app.analytics.com/file.js?123456789 and create 1 cache entry.

In the last update of the plugin a warning and clean-up solution was added that warns when the proxy cache directory grows to more than 500 files and that should automatically empty the cache directory when it grows to more than 5,000 files. Apparently, for some reason the cache directory isn't automatically emptied on your server. The cause might be a file permission problem. You may find a clue for a possible cause in the PHP error log.

In the next version of the plugin, the proxy and cache system will be redone.
