### ISSUE TITLE
Add possibility to call gulp from other path

### ISSUE THREAD

**Issue by Jojolam44** [optimalisatie/above-the-fold-optimization#43]
Hi,

Can you add the possibility to call gulp tasks from an other path ?
I want to be able to call gulp tasks from my main gulpfile (at the root of the theme folder) but each tasks use a variable "taskpath" relative to "abovethefold" folder.
Maybe adding a "mainPath" in the function call can resolve this query ?

Thanks.

**Comment by optimalisatie** [comment]
Hi Jojo,

Thank you for your suggestion!

I've forwarded your request to our engineers. We will look at it for the next update.

Best Regards,
Jan Jaap
info@pagespeed.pro
