### ISSUE TITLE
Above the fold optimization mobile menu not working

### ISSUE THREAD

**Issue by JonbertDavidsen** [optimalisatie/above-the-fold-optimization#46]
Hi, 

When I turn on the Above the fold optimization the mobile menu is not working. 

Initially, I isolated the problem to two plugins: Autooptimize and this one. 

I solved the problem in autooptimze by adding core/js/responsive-scripts.min.js to the exclude list. 

Any ideas how I solve the issue with Above the fold-optimization? 

My website is https://davidsenconsulting.com

**Comment by optimalisatie** [comment]
Hi Jonbert,

Thank you for reporting the issue!

Some scripts do not natively support asynchronous loading. More information can be found in the following article about making Google AdSense scripts async compatible:

https://support.google.com/adsense/answer/3221666?hl=en

To solve the issue quickly it may be an option to exclude the conflicting scripts. For some scripts it may be a solution to encapsulate the code in `jQuery(function($) { ... });` This could be done with a WordPress filter:

```php
function pagespeed_filter_html($searchreplace)
{
    list($search, $replace, $search_regex, $replace_regex) = $searchreplace;

    # rewrite lsjQuery .ready() code
    $search_regex[] = '|(...script code match...)|s';
    $replace_regex[] = 'jQuery(function($) { $1 });';

    return array($search,$replace,$search_regex,$replace_regex);
}
add_filter('abtf_html_replace', 'pagespeed_filter_html', 10, 1);
```

If you use Autoptimize for minification of inline javascript you could use a filter by Autoptimize:

```php
function pagespeed_filter_inline_js($JS)
{
    if (strpos($JS, '(...script code to match...)') !== false) {
        $JS = preg_replace('|(...script code match...)|s', 'jQuery(function($) { $1 });', $JS);
    }
    return $JS;
}
add_filter('autoptimize_js_after_minify', 'pagespeed_filter_inline_js', 10, 2);
```

To understand the issue with async loading: some scripts depend on other scripts and when loading scripts asynchronously, the scripts will try to load as fast as possible independent from each other and independent from the HTML document. For some requests, the javascript files may be executed seconds after the HTML is loaded. For cached requests however, a script may be executed before the start of the HTML body. This may cause issues for some scripts. Using the jQuery encapsulation solution will make a script execute after the HTML is loaded, providing in stability that is sufficient for most scripts. When there are special dependencies however (such as with Google AdSense), it may be a little more complex to solve the issue.

Let me know if you manage to resolve the issue!

**Comment by JonbertDavidsen** [comment]
Hi

Thank you for connecting with me. 

It's not solved yet, but I guess it's because I'm new to this plugin. I'm unsure where to put the code. 

I'm familiar with putting codes into files from cpanel.

I've listed my settings here, hope that can help figure out where I insert this code, and if there something else wrong. 

I use CloudFlare and use developers mode when I configure.

Autooptimize 1 of 3: http://i.imgur.com/3OW3ZaM.jpg
Autooptimize 2 of 3: http://i.imgur.com/NJOAqY6.jpg
Autooptimize 3 of 3: http://i.imgur.com/lghR0Nl.jpg

Above the fold optimization 1 of 6: http://i.imgur.com/FVWYyE4.jpg
Above the fold optimization 2 of 6: http://i.imgur.com/4c43Rmw.jpg
Above the fold optimization 3 of 6: http://i.imgur.com/33wJ8tZ.jpg
Above the fold optimization 4 of 6: http://i.imgur.com/VZ09UiT.jpg
Above the fold optimization 5 of 6: http://i.imgur.com/p05HOzU.jpg
Above the fold optimization 6 of 6: http://i.imgur.com/w8Ks5N9.jpg

Google Page Speed 1 of 2: http://i.imgur.com/8vROubK.jpg
Google Page Speed 2 of 2: http://i.imgur.com/ZYeYBu1.jpg

Does this help?
