### ISSUE TITLE
UnhandledPromiseRejectionWarning - Above the fold css generator

### ISSUE THREAD

**Issue by kaziqta** [optimalisatie/above-the-fold-optimization#47]
Hi,
I am having the following issue in the console, once I run "gulp critical-something":
(node:3467) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error opening url '': Operation canceled
10x
Stefan

**Comment by optimalisatie** [comment]
Hi kaziqta,

The error indicates that Gulp.js is unable to open URLs. It may be that a firewall is blocking internet access or that Gulp.js has no permission to access the network.

For additional support it will be possible to post your issue at critical:

https://github.com/addyosmani/critical

Please let me know if you manage to resolve the issue!

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by kaziqta** [comment]
I am running it from the server, all pointed etc. I am using nginx
