### ISSUE TITLE
Articles page not affected by this plugin

### ISSUE THREAD

**Issue by adrianorgg** [optimalisatie/above-the-fold-optimization#48]
Hello, I've created conditional critical CSS for all the pages of my website; quality test is good for all of them, except for the articles listing page ( https://www.bbmichelangeloapartment.com/bnb-civitavecchia-recensioni/ ). When I perform the qualy test for this page, I see the page completely unstyled, as if it is not affected by the critical css I've created for it.
How can I fix this?
Thanks!

https://www.bbmichelangeloapartment.com/

**Comment by optimalisatie** [comment]
Hi Adrianorgg,

When you enable debug modus and check the location of the critical CSS in the HTML source, it will list the applied critical CSS conditions. If the conditions do not match, the cause lays in the WordPress theme or plugin configuration. It may be that a plugin alters the way that the page is rendered bypassing regular WordPress conditions.

**Comment by adrianorgg** [comment]
Yes, I checked the html source of that page and I saw that only the critical CSS for Google Fonts is inserted in the page, while the rest is missing, and this happens only in the blog page; in all the other pages and posts the critical css is complete. I will contact the theme developer to understand whre the problem is.
Thanks
