### ISSUE TITLE
Retain attributes in script tags

### ISSUE THREAD

**Issue by pra85** [optimalisatie/above-the-fold-optimization#49]
Firstly thanks for this awesome plugin 

I added the following script in my site -

`<script src="//load.sumome.com/" data-sumo-site-id="ed5c47a02ba6e04566a1f4b42b301c56cadc89505e6961cc7eed2a2171cf0eb4" async="async"></script>`

But when I enabled the JavaScript optimization, it seems to strip away the `data-sumo-site` which is critical for this script to work. I can make it work by adding it to the Ignore List but is possible that it can be asynchronously loaded while retaining the attributes

**Comment by optimalisatie** [comment]
Hi @pra85,

Thank you for your feedback!

Regrettably, the current async script loader does not support preserving custom HTML attributes. It would also be doubtful that an (external) service that depends on it would be compatible with script-injected scripts. A solution may be to add a second inline script container with the `data-sumo-site-id` attribute that is then excluded from optimization/minification (e.g. Autoptimize). I've checked the code from `//load.sumome.com/` quickly and it appears that the `data-sumo-site-id` attribute is just used to determine the ID of the site.

The new HTML for the propose solution would look as following:

```html
<script data-sumo-site-id="ed5c47a02ba6e04566a1f4b42b301c56cadc89505e6961cc7eed2a2171cf0eb4"></script>
<script src="//load.sumome.com/" async="async"></script>
```

The Autoptimize exclude filter would be `data-sumo-site-id`.

Please let us know if this resolves the issue!

Best Regards,
Jan Jaap
info@pagespeed.pro
