### ISSUE TITLE
Web Font Optimization - Strange Issue

### ISSUE THREAD

**Issue by MartyD23** [optimalisatie/above-the-fold-optimization#50]
Hi,

In the Web Font Optimization section i have saved a list of fonts in the "include" list and specified some different fonts in the "exclude" list.

I wanted to do this because my theme by default was loading many fonts i wasn't actually using.

The trouble is, after i save and navigate away from the page and browse my site, when i go back to the "include" list other fonts have been added to it for some reason.

For example, I save my include list with the following fonts:

Open Sans:400italic,400,600,700:latin
Unkempt:400,700:latin
Indie Flower:400:latin

After browsing my site when i go back to look at the list it's added extra fonts by itself as such:

Open Sans:400italic,400,600,700:latin
Unkempt:400,700:latin
Indie Flower:400:latin
Open Sans:400,700:latin
Open Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800:latin
Calligraffitti:400:latin
PT Serif:400,400italic,700,700italic:latin
Crafty Girls:400:latin
Crete Round:400,400italic:latin
Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic:latin
Source Sans Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic:latin

In the exclude list i have specified the following:

Calligraffitti
PT Serif
Crafty Girls
Crete Round
Lato
Source Sans Pro

Not sure if i'm doing something wrong here? But i have left the "WebFontConfig" section that is above the include list blank. Should i be specifying the font families here also? I'm not sure how to correctly do that?

When i view the source for my pages, only the fonts i had originally specified are shown so it looks like its working as it should, that is until i go back to look at the include list and see it's been changed somehow.

Thanks for any help you can provide.

**Comment by optimalisatie** [comment]
Hi @MartyD23,

Thank you for reporting the issue!

Based on your feedback we've included two new options in `v2.7.11` that enable to turn off automatic font discovery and/or configure an ignore list to exclude fonts from being included in the optimization. The exclude list has been renamed to `Remove List`.

![image](https://user-images.githubusercontent.com/8843669/28593520-d904ca8e-718c-11e7-9f8f-428238bcdac1.png)

Best Regards,
Jan Jaap
info@pagespeed.pro
