### ISSUE TITLE
Using with Delicious Brains S3 Cloudfront plugin

### ISSUE THREAD

**Issue by mrbm** [optimalisatie/above-the-fold-optimization#53]
wondering where your plugin re-renders items in the css, and then after re-rendering wondering if its possible to check if this https://wordpress.org/plugins/amazon-s3-and-cloudfront/ plugin is active and then use the plugin's filter to filter the image results so that they point to the correct s3 paths....

Usage is simple:

$content = apply_filters( 'as3cf_filter_post_local_to_s3', $content );

Right now my background images are pointing to local paths unfiltered.

Thoughts?

**Comment by optimalisatie** [comment]
Hi @mrbm,

The ABTF plugin does not re-render/optimize/compress CSS. It uses filters from other plugins such as Autoptimize to optionally optimize `@import` based Google WebFonts in CSS code. It doesn't process images or URLs so it is unlikely the cause.
