### ISSUE TITLE
little-loader + HTML5 Web Worker and Fetch API based script loader with localStorage cache

### ISSUE THREAD

**Issue by emanueltomasinborda** [optimalisatie/above-the-fold-optimization#58]
Hi, when you enable that option pagespeed stops working, you can not complete the test. I hope they solve it soon. Thank you very much.

**Comment by optimalisatie** [comment]
Hi emanueltomasinborda,

The client code of `2.8.10` has been optimized with Google Closure Compiler. Could you please verify if it has resolved the issue?

**Comment by emanueltomasinborda** [comment]
Hi, I did not solve the problem, thank you very much for your attention, regards.

**Comment by optimalisatie** [comment]
Hi emanueltomasinborda,

Could you please let us know the URL that you are testing with? You could send it to info@pagespeed.pro.

Thanks a lot for your feedback!
