### ISSUE TITLE
Proxy Scripts enabled but still receive "Leverage browser caching" for analytics.js

### ISSUE THREAD

**Issue by pokerjk** [optimalisatie/above-the-fold-optimization#59]
Hi,

I am still receiving the "Leverage browser caching" for https://www.google-analytics.com/analytics.js after checking Proxy Scripts, you can see my settings here https://image.ibb.co/fuRVNF/settings.png

Do I need to configure anything more?

Website URL: https://goo.gl/c29twv

Thanks

**Comment by xRahul** [comment]
Looks like you've not entered `google-analytics.com/analytics.js` in the Proxy include list. Have you tried that?
