### ISSUE TITLE
Manifest.json doesn't load right in the editor

### ISSUE THREAD

**Issue by Vidyut** [optimalisatie/above-the-fold-optimization#62]
This has been there from the last couple of versions at least. Forgot to report because the app is still evolving rapidly on a daily basis, plus it didn't really bother me, since I already had a manifest file.

http://imgur.com/thbyLMa

[clarification: the manifest exists and works and the site is consistently scoring green https://aamjanata.com - it isn't a file problem. The permissions are set correctly too.]

**Comment by optimalisatie** [comment]
Hi Vidyutk,

Thanks a lot for the feedback!

It appears that PHP's `json_decode()` fails indicating that the JSON may be invalid.

`v2.8.15` contains a warning if the parsing of JSON fails.
