### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Vidyut** [optimalisatie/above-the-fold-optimization#65]
A checkbox for whether you want the plugin to empty the cache or not. Sometimes the changes are minor and it is fine if the cache updates naturally whenever it will and is not worth dumping the performance of already cached pages over.

**Comment by optimalisatie** [comment]
Hi Vidyut,

Thank you for the suggestion! 

The suggested option is already available on the settings panel:

![image](https://user-images.githubusercontent.com/8843669/29878274-63cc6d58-8da2-11e7-98c5-b6e721aeb68e.png)

If you have more suggestions / feature requests, please let us know!

**Comment by Vidyut** [comment]
#Facepalm

Thanks

**Comment by gnanet** [comment]
Maybe Its just me, but the minify file cache in w3tc seemed not to be erased upon saving changes in abtf settings. Also i assume criticalcss changes over ftp cannot be caught by this function.
