### ISSUE TITLE
When using importScripts to load the service worker, the json config might not load

### ISSUE THREAD

**Issue by 16patsle** [optimalisatie/above-the-fold-optimization#66]
I am currently setting up the PWA functionality but I had to use importScripts to import the service worker, to make it work with OneSignal push notifications. I ran into an error because all relative scripts are loaded relative to the entry script. For that reason, when the PWA script tries to load `./abtf-pwa-config.json`, it is resolved from the directory where my other script, the entry script, is located. Are there any possibility to change the path it is loading from?

I basically have two ideas: 
1. Use an absolute path, like `/abtf-pwa-config.json`.
2. Use PHP to generate the path to the file dynamically.

The best would probably be to combine the two. Generate an absolute path to the file (from the root directory) when the file is generated.

(By the way, I think you have a typo on the PWA page. `includeScript`instead of `importScripts`)

**Comment by optimalisatie** [comment]
Hi 16patsle,

Thanks a lot for the feedback!

`v2.9.0` contains the path configuration in the query string:

```javascript
importScripts('abtf-pwa.js?path=/custom/path/');
```

Optionally, it is also possible to customize the JSON config filename using the parameter `&config=`.

**Comment by 16patsle** [comment]
Thanks! I'm going to play around with this as soon as I have time.
