### ISSUE TITLE
Warning: trim() expects parameter 1 to be string

### ISSUE THREAD

**Issue by FernandoAsB3** [optimalisatie/above-the-fold-optimization#67]
when I active the Optimize Javascript Loading and save, I have this problem

**Warning:** trim() expects parameter 1 to be string, array given in /home/acunningham/public_html/wp-content/plugins/above-the-fold-optimization/admin/admin.class.php on line 879

**Warning:** Cannot modify header information - headers already sent by (output started at /home/acunningham/public_html/wp-content/plugins/above-the-fold-optimization/admin/admin.class.php:879) in /home/acunningham/public_html/wp-includes/pluggable.php on line 1210

![image](https://user-images.githubusercontent.com/16619483/30118296-45550bdc-92e8-11e7-8090-488e18d21ab2.png)

**Comment by optimalisatie** [comment]
Hi FernandoAsB3,

Thank you for reporting the bug! The issue has been fixed in `v2.9.0`.
