### ISSUE TITLE
Minify HTML breaks WP API response

### ISSUE THREAD

**Issue by johanhermansson** [optimalisatie/above-the-fold-optimization#68]
JSON structure breaks if Minify HTML checkbox is checked. HTML elements within post_content.rendered with a space directly after the opening tag is converted into a line break.

```html
<a href="/">Link</a>
```
is transformed into

```html
<a
href="/">Link</a>
```

inside the JSON answer.

I guess this is a problem on other rendered parts of the answers.

This makes the JSON structure broken and parsers will not return anything.

Right now I need to replace these element line breaks before trying to parse the response.

```javascript
return responseText.replace(/<([a-z])+\n/g, '<$1 ');
```

**Comment by optimalisatie** [comment]
Hi johanhermansson,

Thank you for reporting the bug!

The ABTF plugin has been disabled for REST API requests since `v2.9.0`.

```php
/**
 * Disable for REST API requests
 */
if (defined('REST_REQUEST') && REST_REQUEST) {
    return false;
}
```
