### ISSUE TITLE
Use URL for CriticalCSS condition

### ISSUE THREAD

**Issue by Emilybkk** [optimalisatie/above-the-fold-optimization#72]
I would suggest to add the URL for the Critical CSS Conditional as the search box can't really search all page. 

I just have problem that I can't search for my contact page. It show only my other post that include "contact" in title. So if we could use URL it will be much better in this case or make the search box really search all posts/page.

**Comment by optimalisatie** [comment]
Hi Emilybkk,

Thank you very much for your suggestion! We've added the feature in the latest update.

The search is based on the WordPress slug so if you would enter an URL or path, it will try to extract the slug from the URL. To quickly search by slug you could simply add the prefix `/`, e.g. `/contact` to search for the contact page.

https://codex.wordpress.org/Class_Reference/WP_Query#Search_Parameter
