### ISSUE TITLE
i unistall this plugin but working background need help pls

### ISSUE THREAD

**Issue by meoman** [optimalisatie/above-the-fold-optimization#73]
Fixed problem reinstall , and close all setting after deleting cache done!

**Comment by meoman** [comment]
[url=https://hizliresim.com/yzlJ19][img]https://i.hizliresim.com/yzlJ19.jpg[/img][/url]

**Comment by optimalisatie** [comment]
Hi meoman,

It may be that a page cache remembered the ABTF optimized version of HTML or assets. 

Please let us know if the issue is resolved!
