### ISSUE TITLE
E_WARNING: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by accell** [optimalisatie/above-the-fold-optimization#74]
Not exactly sure what's causing this, but NewRelic is of course letting me know about it:

<img width="686" alt="screen shot 2017-10-05 at 9 10 59 pm" src="https://user-images.githubusercontent.com/5078828/31259061-e704b974-aa11-11e7-8b62-03ef1b1f007e.png">

**Comment by optimalisatie** [comment]
Hi accell,

Thank you for reporting the issue!

The issue appears to be a conflict related to W3 Total Cache. We will be looking into it.
