### ISSUE TITLE
Support for: WP Merge + Minify + Refresh

### ISSUE THREAD

**Issue by scysys** [optimalisatie/above-the-fold-optimization#76]
Did not find: https://de.wordpress.org/plugins/merge-minify-refresh/ in your compatibility list. Please check :)

**Comment by optimalisatie** [comment]
Hi!

It would be possible to write a plugin module and submit it to info@pagespeed.pro. We will then include it with the next update.

https://github.com/optimalisatie/above-the-fold-optimization/tree/master/trunk/modules/plugins/
