### ISSUE TITLE
Specified https://mycdn.domain.com/path for proxy but it uses http

### ISSUE THREAD

**Issue by supernovae** [optimalisatie/above-the-fold-optimization#77]
I specified my proxy domain for caching javascript files as https:// but noticed when my code wasn't working that it was switching to http://mycdn.domain.com/...

**Comment by optimalisatie** [comment]
Hi supernovae,

Thank you for reporting the issue! The issue has been resolved in the latest update.

**Comment by supernovae** [comment]
thanks! seems to be working now, just having an issue with the cache path being inserted twice in the URI. Submitted a ticket for that. Will close this one.
