### ISSUE TITLE
CSS Loaded Callback

### ISSUE THREAD

**Issue by ChipRyan** [optimalisatie/above-the-fold-optimization#79]
Is there any way we can define a callback function after all the stylesheets have been rendered? I can't seem to find any way to do so in the plugin.

**Comment by optimalisatie** [comment]
Hi ChipRyan,

Thank you for your suggestion! Regrettably, the ABTF plugin does not support it. You would need to seek a manual solution, for example by polling `document.styleSheets`.

Our upcoming Advanced Optimization plugin will contain a callback feature and offers many more options for fine grained control over both loading and rendering. Our engineers are working very hard to complete the plugin a.s.a.p.
