### ISSUE TITLE
google webfont.js - wrong version?

### ISSUE THREAD

**Issue by jimwalczak** [optimalisatie/above-the-fold-optimization#82]
We're experiencing trouble as your plugin tries to load webfont.js v1.6.28 - but that 404s - Google only shows v 1.6.26 - Github shows the release of 1.6.28

We'd like to serve from Google CDN - please advise

Thanks

**Comment by supernovae** [comment]
I saw this in my developer console as well.

**Comment by jimwalczak** [comment]
I found the work around - look at the field below where it loads the script - where it refers to v1.6.28 manually change to 1.6.26

**Comment by optimalisatie** [comment]
Thanks a lot for reporting the issue! The issue has been resolved in the latest update.
