### ISSUE TITLE
Css Delivery - loadCSS preload pattern

### ISSUE THREAD

**Issue by Kilbourne** [optimalisatie/above-the-fold-optimization#83]
Is possible to use preload+polyfill for css delivery ( actual loadCSS recommended pattern) ?

I'm having this trouble with the styles order:
"Manual CSS loading with loadCSS - loadCSS will reference CSS files in the order they are called, but keep in mind that they may finish loading in a different order than they were called."
The preload should ensure right order.

**Comment by optimalisatie** [comment]
Our new plugin will be improved to maintain order and it will provide an option for `rel="preload" as="style"` based async loading. The new plugin will introduce several new innovations such as responsive CSS loading (which also works without `rel="preload"`), optional `requestAnimationFrame` rendering and localStorage caching to bypass the network interface which provides significant faster CSS loading (especially on mobile devices). The plugin will also introduce async and responsive javascript execution, HTML fragment streaming and async HTML fragment loading using a Service Worker. 

Async javascript execution will enable script execution prioritization using `requestIdleCallback`, `requestAnimationFrame`, `domready`, (element) `inview` or a Media Query and it is compatible with concatenated scripts. This feature will provide a great performance advantage for most websites as complex javascript is one of the greatest frontend performance drags that is growing each year. The average size of scripts on a page grew with +300% in the past 5 years according to a study by KeyCDN, a big CDN provider. Async script execution prioritization will be a solution that enables heavy and complex javascript with super fast first page load experiences for any website.

We've experienced some funding issues in the past year. There are new investors from the US and the UK an our engineers are working very hard to complete the plugin a.s.a.p. We are expecting that a first beta will be available in 2-3 months.

If you require a solution right now, it may be an option to edit the loadCSS source file and rebuild the client using Grunt. The source files and Gruntfile.js are included in the plugin directory. 

The command to build the client (with modified sources) is `grunt build`.
