### ISSUE TITLE
Failed to write to: ../wp-content/cache/abtf/

### ISSUE THREAD

**Issue by jhoylman** [optimalisatie/above-the-fold-optimization#84]
Hello all!  I recently installed this plugin, configured it, and love it so far!
Just noticed that for some reason the proxy is not working.  I am getting a "Failed To Write" to the /wp-content/cache/abtf/ directory.

I have verified permissions for this directory is set to 755.  Also tried it at 666.

The directory only has one file in it, which is "cleanup_cron.log"

Any ideas why it can not write to this directory?

Thanks!
Jared

**Comment by optimalisatie** [comment]
Hi Jared,

The issue is related to server permissions. It would be best to seek advise with your hosting provider or a server engineer. The issue may be related to the PHP / nginx user specific permissions.
