### ISSUE TITLE
Critical CSS is implimented to use a theme directory as default...bad

### ISSUE THREAD

**Issue by mrbm** [optimalisatie/above-the-fold-optimization#89]
Plugin is giving warning:

/wp-content/themes/theme-name/abovethefold/css/

As a default it should be using the sites upload directory. Using the theme directory is not a good strategy:

1. If this is a multi-site set up...bad
2. If the theme is a symlink...bad

Or maybe I'm wrong...thoughts?

**Comment by optimalisatie** [comment]
Thank you for your feedback!

The critical CSS is part of a theme just like `style.css` or theme related CSS files in /css/.

Could you provide an example when it would cause issues with a specific WordPress setup/usage?

**Comment by mrbm** [comment]
one way to manage multiple sites on a single server is to use symlinks. Wordpress started supporting this set up, but if all the sites are using a symlink to a single theme, then when above the fold creates a folder in that theme...its like creating that folder in all the themes at once.  Same with a multi-site environment.

Autoptimize and other various caching plugins handle the writing of data in a multisite environment like this:
/wp-content/cache/autoptimize/15/css/autoptimize_a3bac757ac26e61fe7f37b5895011f90.css

With 15 being the Site ID

You could do the same.

Thoughts?

**Comment by optimalisatie** [comment]
The difference with Autoptimize CSS cache is that it's page (WordPress site) specific while critical CSS is a part of a theme (just like `style.css` isn't added separately for each site that uses the theme).

In the current setup it would be possible to create a custom critical CSS condition that applies critical CSS conditionally based on the site.

Example:

```php
/**
 * Critical CSS Condition
 * Apply critical CSS based on site ID
 */
function themename_criticalcss_condition( $params = array() ) {
	$blog_id = get_current_blog_id();

	// Site 1 or 4?
	if (in_array($blog_id,[1,4])) {
		return true; // apply critical CSS
	}

	return false; // ignore 
}
```

In the filter configuration you can then select the condition by typing `filter:themename_criticalcss_condition`.

![image](https://user-images.githubusercontent.com/8843669/28587022-fa7626d4-7175-11e7-8634-db2f1ca78312.png)

We will consider your feedback for making it easier to create critical CSS for a multi site that uses the same theme for multiple sites.

**Comment by mrbm** [comment]
I see...well do your best!

**Comment by optimalisatie** [comment]
Our new plugin will not specifically enable critical CSS for multi-site sites. It will remain theme based. The plugin will provide an improved conditional system that will enable to load critical CSS as mentioned above, as well as via some new PHP based methods.

If you have a suggestion for an improvement for usage on multi-sites, please let us know!

**Comment by mrbm** [comment]
smh
