### ISSUE TITLE
External scripts such as ads, Analytics, etc not loading when PWA is enabled

### ISSUE THREAD

**Issue by earcos** [optimalisatie/above-the-fold-optimization#90]
Hi, for some reason as soon as I enable PWA, external scripts such as ads (Doubleclick) Google Analytics and similar content is not loaded. Seems like the serviceworker blocks any external resource. Any pointers on fixing this behaviour?

Thanks a lot!

**Comment by optimalisatie** [comment]
Hi earcos,

Thank you for your feedback!

As you can see on our demo website www.e-scooter.co that uses the Service Worker / PWA with Google Ads, it doesn't break the ads.

We have the following questions:

1) Do you have debug mode of the plugin enabled?

2) Is there an error or notice visible that could be related to the issue?

Loading the script via the service worker provides a local caching advantage which would make the ads faster, however, it would be possible to specifically exclude the Google AdSense related scripts from being loaded via the Service Worker. You need to add an entry to the assets cache configuration with the option `"not":true`, like added by default to exclude Google Analytics for images.

![image](https://user-images.githubusercontent.com/8843669/35703458-5f158276-079c-11e8-9faa-d2fab01ffb13.png)

**Comment by earcos** [comment]
Hi, thanks for the super fast answer. We don't use Adsense, we use Doubleclick with async calls, not sure if this has something to do with my issue.

The only error I get on the console is: "net::ERR_FAILED" with references to the abtf-pwa.js file. 

I also added specific calls to Analytics, Doubleclick and other scripts on the cache assets editor, but still ads are not loading 😞 

Thanks again for answering so fast and thank you for all your amazing work.
