### ISSUE TITLE
WordPress blocking our plugins for almost 1 month + censorship + forum ban

### ISSUE THREAD

**Issue by optimalisatie** [optimalisatie/above-the-fold-optimization#96]
We have been victim of horrible actions by WordPress management. The reason is unknown. We have no clue to the exact origin / motive but it's truly criminal what's been done.

We have been creating a comprehensive update for the ABTF plugin that includes a massive amount of unique website performance innovation and much requested features such as CSS and javascript code optimization, minification, concatenation etc.

The plugins are available here: https://github.com/o10n-x

Regrettably, WordPress has been blocking plugin submission for almost a month already. 

**Why are the plugins blocked?**

Reason 1: WordPress has demanded that we remove our company name **PageSpeed.pro**

> we fear that Google will hurt the WordPress community with legal actions against the directory.

It seems a bit odd to fear such a thing when Google has recently made a deal with WordPress to dedicate a team to optimizing the WordPress core. Also, we have a Harvard-degree lawyer on our team and Google has no right on our company name or domain.

**The need for speed: Google dedicates engineering team to accelerate development of WordPress ecosystem**
https://searchengineland.com/need-speed-google-dedicates-engineering-team-accelerate-development-wordpress-ecosystem-291214

We did plan to change the name so we already changed the name to **Optimization.Team** to reflect the target and purpose of the new company, a simple purpose of working towards enhancing knowledge and quality in website optimization technologies.

After 2 weeks, our Web Font Optimization plugin was published.

https://wordpress.org/plugins/web-font-optimization/

We initiated the publication of the CSS optimization plugin and that is now also blocked for weeks.

Reason 2: WordPress demands that our plugin namespace **O10n** needs to be renamed, which is impossible. They ignore our explanation that the plugins are designed to use the namespace to achieve single plugin performance when using 10+ optimization plugins. The PHP memory usage will be of just 1 plugin etc.

They ignore this with a disrespectful comment and are now blocking our optimization plugins for weeks and maybe indefinitely.

### WordPress moderator:

> > **It is correct that the namespace O10n will be reused. ...**
> 
> Just FYI... we don't need to know about the rest 
> 
> Here's what YOU should bear in mind: The top 'tier' of whatever you're using to make your code unique MUST be different for each plugin and theme.
> 
> If you put it all in a class, the class must be unique and distinct for that plugin.
> 
> If it's in a namespace, then that's got to be unique for the plugin.
> 
> The other way ends in conflicts and tears 
> 
> And now you know. Don't re-use namespaces 
> 
> -- 
> Ipstenu (Mika Epstein)

## Evidence for censorship

Our posts on WordPress are censored and we are banned from the forum. There is evidence for censorship as **WordPress literally deleted our comments to a user** from the forum. As you can see, the user replied to a comment that was initially published.

![wp-evidence-censorship](https://user-images.githubusercontent.com/8843669/36895430-243bf26e-1e0f-11e8-9c55-f3a88d3054eb.jpg)

This is criminal.

## Slander attack

Some time ago the original author of the ABTF plugin became victim of a slander attack by a WordPress moderator. The author got smeared as a spammer for posting the simple **regards, name, email** under quality support replies. The moderator spent several hours to replace the signature with a link to anti-spam in ‘100 posts’, linking to a WordPress policy text that states that **advertising in topics unrelated to your own plugins or themes is not allowed**.

The attack seemed to have come out of the blue. And it has remained as such until today. 

The author had no idea what their intentions could have been. He only suspected that it could have been sign for worse (100 spam notices for a plugin that provides a pagespeed 100 score, which costs hours to do, is a remarkable action), so he instantly discussed it publicly on a forum which caused people to pay attention to the actions of WordPress management very early, which may have offset their original plans, causing them to choose to remain silent.

**WordPress never had the decency to contact the author until today.**

The author does not know why WordPress didn’t decide to simply contact him to explain what went wrong. After all, up until now he has simply provided a free technology + free quality support for 20.000 users on the WordPres platform, mostly users who use WordPress for more serious matters such as business, and users who expressed to be happy with the plugin.

For the record: the author was never involved in any form of spam, not email or SEO related. In fact, he is specialized in "white hat SEO" and has ran a business advertising / practicing "ethical SEO" since 1999.

I understand that there is nothing that any user can do but we are obligated to share this information as users are hurt by not being able to access our plugins / the latest optimization technologies.

Any feedback / tips for handling the situation are appreciated!

**Comment by futtta** [comment]
Hey Jan-Jaap.
I'd be happy to try to help you sort out any communication issue you might be facing!
Who have you been in contact with, forum moderators or the plugin-team? 

met vriendelijke groeten,
frank (autoptimize)

**Comment by optimalisatie** [comment]
For a complete picture, hereby our latest conversation with WordPress. We have been very decent and correct in our communication at all times. Never were there emotions at play etc.

WordPress does not respect our plugin design on the basis of hypothetical arguments that have no substance in regards to the reality of our plugins. Despite this being communicated clearly, the plugin has remained blocked for more than 1 week while they keep processing their useless / already debunked argument.

> 
> -------- Forwarded Message --------
> Subject: 	Re: [WordPress Plugin Directory] Request: CSS Optimization
> Date: 	Sat, 3 Mar 2018 19:19:58 +0100
> From: 	Optimization.Team <info@optimization.team>
> To: 	plugins@wordpress.org
> 
> 
> Thank you for your concern. In regards to your statement
> 
> >   **If you’re sure you don’t care about the future** 
> 
> We are not sure what to make of this but it can be added to the list...
> 
> We do care about the future and we like to use namespaces for the intended usage.
> 
> Thanks in advance for your time to review the plugin!
> 
> On 03/02/2018 11:56 PM, Ipstenu (Mika Epstein) wrote:
> > Yes these are hypothetical but VERY common. Like daily common.
> >
> > Seriously. We’re trying to help you not shoot yourself in the foot here. In the long run, you’re raising your risk for no good reason, and we want to help you ... y’know, not.
> >
> > We are literally trying to watch your back for you.
> >
> > If you’re sure you don’t care about the future, we can and will approve this, but we would be negligent if we didn’t take the time to make SURE. 
> >
> 
> 
> -------- Forwarded Message --------
> Date: 	Fri, 2 Mar 2018 23:35:16 +0100
> From: 	Optimization.Team <info@optimization.team>
> To: 	plugins@wordpress.org
> 
> 
> Hi Otto,
> 
> Thank you for your reply.
> 
> We use namespaces for performance optimization. We've provided a sufficient explanation. The conflicts that you are talking about are hypothetical with no substance in regards to the reality of our plugins.

> 
> > What happens if someone uses the same function or class name in two plugins?
> 
> The namespace is used for the plugin core. It enables to achieve single plugin performance while using 10+ individual plugins. There is no possibility for a conflict because the plugins are designed to be used together.
> 
> For public methods it may be that a different namespace is used. As an example, the existing plugin CloudFront Page Cache has been updated with the new optimization structure and uses the O10n namespace. The public methods however, have a different namespace, O10n\CloudFront.
> 
> The plugin works together with the Web Font Optimization plugin. When both plugins are installed, the namespaced class files of just one of the plugins are loaded. This saves a lot of PHP memory and the plugin design enables further optimization options using this design.
> 
> 
> 
> When the O10n namespaced plugins are used together, the plugins will perform as a single plugin. This will reduce PHP memory usage significantly when using many optimization plugins. Users of the ABTF plugin will need to install 5 to 7 optimization plugins to use all the optimization features in the new concept, so this is the reason that the shared namespace based optimization is important to reduce plugin related overhead.
> 
> 
> 
> On 03/02/2018 03:11 PM, Samuel Wood (Otto) wrote:
> > Also, you may be operating under a misconception. Namespaces do not affect performance in any way. That's simply not how namespaces work in PHP.
> >
> > Namespaces are a convenience only. They exist for the purpose of organization and creating well-structured code. Internally, PHP doesn't actually have "namespaces". The function lookup table is the same global one for all functions. The only thing a namespace does is to add a prefix onto all the functions it applies to.
> >
> > So, if I do something like this:
> >
> > function example() {}
> >
> > and then namespace another one:
> >
> > namespace foo;
> > function example() {}
> >
> > Then the internal function table will have these in it:
> >
> > "example"
> > "foo\example"
> >
> > That's it, that's literally all that namespaces do. Namespaces do not exist as a structure in PHP and do not have any impact on performance at all.
> >
> > -Otto
> >

> > 
> > -------- Forwarded Message --------
> > Subject: 	Re: [WordPress Plugin Directory] Request: CSS Optimization
> > From: 	Ipstenu (Mika Epstein) <plugins@wordpress.org>
> > Date: 	Wed, 28 Feb 2018 16:18:41 +0000
> > To: 	info@optimization.team
> > 
> > 
> > > As explained in the previous email. The namespace O10n is intended to be
> > > shared by our plugins. The plugins do not use namespace to prevent
> > > overlap, they use it to overlap and obtain single plugin performance.
> > 
> > That's a really REALLY really bad idea.
> > 
> > What happens if someone uses the same function or class name in two plugins?
> > 
> > If you're adamant that this is the way you must do things, then we will approve it, but in our experience with plugins and development (and combined, we've been doing this for as long as there have been computers) this is a BAD idea. This WILL backfire when you have a rookie dev who doesn't know all your functions. And you will end up having to change it. Better sooner than later IMO.
> > 
> > -- 
> > Ipstenu (Mika Epstein)
>

**Comment by Otto42** [comment]
@optimalisatie If you post private emails from the plugins team to the public without obtaining permission again, we will ban you from WordPress.org.

At no point have you been under attack. At no point have we been "holding up" your submissions. 

You submitted plugins with the same namespaces. We told you why that is a bad idea. Because it is, no matter what you happen to think about the matter. You wanted to argue with us and then you wanted to posts like we're attacking you.

The forum moderators put your account on watch because you started telling people that we were the problem, and because of this little rant you posted here. Today, you did it again, 8 hours after we allowed your plugin to be published, with the bad namespaces and all.

Why you're trying to pick a fight, I have no idea. But, just stop. Continued behavior like this on the forums or elsewhere will get you and your plugins removed from the directory. We manage the directory and try to prevent problems pro-actively. If you're pro-actively trying to cause problems, then we will put an end to it.

**Comment by Otto42** [comment]
Oh, and a moderator removing your signatures from your posts is not a "slander attack". It's them removing signatures, because as it says in the forum rules, signatures are not allowed.

**Comment by optimalisatie** [comment]
I was providing high quality support and most users used the same signature, which is simply a polite thing to do.

> "Best Regards,
> Jan Jaap
> info@pagespeed.pro"

I was never warned and the link pointed to a rule stating that "_advertising in forums unrelated to your own plugins and themes is not allowed_". That is not a correct action to do, and doing that 100 times is not an accident.

**Why did I post a signature? It was functional:**

An innovation plugin often requires users to provide sensitive data or a way to contact for additional / complex support. 

I didn't deserve an aggressive smearing link to anti-spam in 100 posts that I had invested so much of my time on. That was simply criminal to do to me!

And why keep silent? Why delete my polite response to the moderator?

Why didn't you contact me to resolve the issue? I would have listened to your explanation. 

You kept silent, and that proved something!

There's something very wrong with the way you've been treating me. I am a honest plugin author who has invested a ton of time for free.

I am for open and free communication. Transparancy, because I have nothing to hide.

I can tell you that I have a lot of experience with conflicts, as an admin, and never ever have I deleted messages or disadvantaged anyone for sharing their perspective or truthful information that I may not agree with. So if you want to ban me from WordPress.org for sharing a truthful perspective on what has happened to me, which affects users of my free plugins (which makes it my obligation), then that's a crime that I will condemn you for.

**Comment by Otto42** [comment]
> I was providing high quality support and most users used the same signature, which is simply a polite thing to do.

It's a thing to not do because it is *not allowed*.

https://make.wordpress.org/support/handbook/forum-welcome/#avoid-signatures

> Avoid Signatures
> As everyone’s username and gravatar is listed alongside their post, it is unnecessary to provide a signature in the WordPress forums. Signatures will be removed by moderators.

That's what they did, they removed your signature. The fact that they had to do it from 100 posts is annoying because it shows that you were not following the rules of the forum. Follow the rules.

> I didn't deserve an aggressive smearing link to anti-spam in 100 posts that I had invested so much of my time on. That was simply criminal to do to me!

No, what is "criminal" is that you wasted the time of our volunteer moderation staff by forcing them to go and edit a hundred posts or so.

> Why didn't you contact me to resolve the issue? I would have listened to your explanation.

The issue was resolved just fine. They removed your signature and linked you to the rules. 

FOLLOW THE RULES. Like everybody else.

> So if you want to ban me from WordPress.org for sharing a truthful perspective on what has happened to me, which affects users of my free plugins (which makes it my obligation), then that's a crime that I will condemn you for.

I will not ban you for having an opinion. I will ban you for not following the rules or for violating common sense privacy standards.

Do not post anybody's private emails in public without permission again. 

I don't know why you seem to think you are special and above the rules, but you are not.
